version: '3'

services:
  fast_api:
    container_name: fast_api
    build:
      context: fast_api
    image: fast_api
    environment:
      PYTHONUNBUFFERED: 1
      SENTRY_DSN: ${SENTRY_DSN}
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: app
    networks:
      - ugc_service

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fast_api
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/
    networks:
      - ugc_service


networks:
   ugc_service:
     name: ugc_network
