name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.7, 3.8, 3.9]

  build:

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.version}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install flake8-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with styleguide
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config=flake8.cfg

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#     - name: Mypy
#       run: |
#         # stop the build if there are Python syntax errors or undefined types
#         mypy .
